version: '3.8'
services:
  app:
    build: .
    container_name: bistime-app
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env

  server:
    build: ./infra/nginx
    container_name: convey-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/letsencrypt
